---
proxy-groups:
- name: NONPROXIED-CLIENT-166
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  use:
  - Proxy-For-Client-166
- name: PROXIED-CLIENT-166
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  use:
  - Proxy-For-Client-166
rules:
- RULE-SET,rule-nonproxied-166,DIRECT
- RULE-SET,rule-proxied-166,PROXIED-CLIENT-166
- MATCH,GLOBAL
rule-providers:
  rule-proxied-166:
    type: http
    behavior: classical
    path: "./rule_provider/rule-proxied"
    url: https://raw.githubusercontent.com/kripul/OpenClashConfig/main/rule-proxied.yaml
    interval: 60
  rule-nonproxied-166:
    type: http
    behavior: classical
    path: "./rule_provider/rule-nonproxied"
    url: https://raw.githubusercontent.com/kripul/OpenClashConfig/main/rule-nonproxied.yaml
    interval: 60
proxy-providers:
  Proxy-For-Client-166:
    type: file
    path: "./proxy_provider/clientaproxy.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  Proxy-For-Client-167:
    type: http
    path: "./proxy_provider/Proxy1.yaml"
    url: https://openclashconfig.pages.dev/proxy1.yaml
    interval: 60
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300

mode: rule
log-level: silent
allow-lan: true
